package gui;

import dao.StudentDao;
import dao.TeacherDao;
import dao.UsersDao;
import pojo.Student;
import pojo.Teacher;
import pojo.Users;

import javax.swing.*;
import java.awt.event.ActionEvent;

public class ChangePassword extends javax.swing.JDialog {

   private Users user;
    public ChangePassword(java.awt.Frame parent, boolean modal,Users users) {
        super(parent, modal);
        user=users;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        list1 = new java.awt.List();
        currentPWLabel = new javax.swing.JLabel();
        newPWLabel = new javax.swing.JLabel();
        confirmPWLabel = new javax.swing.JLabel();
        changePWLabel = new javax.swing.JLabel();
        currentTxt = new javax.swing.JPasswordField();
        newTxt = new javax.swing.JPasswordField();
        confirmTxt = new javax.swing.JPasswordField();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        currentPWLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currentPWLabel.setText("Current Password:");

        newPWLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newPWLabel.setText("New Password:");
        newPWLabel.setToolTipText("");

        confirmPWLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        confirmPWLabel.setText("Confirm New Password:");
        confirmPWLabel.setToolTipText("");

        changePWLabel.setForeground(new java.awt.Color(117, 86, 253));
        changePWLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        changePWLabel.setText("Change Pasword");
        changePWLabel.setToolTipText("");

        currentTxt.setColumns(12);
        currentTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N


        newTxt.setColumns(12);
        newTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        confirmTxt.setColumns(12);
        confirmTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        confirmBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(149, 149, 149)
                                                .addComponent(changePWLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(154, 154, 154)
                                                .addComponent(confirmBtn)
                                                .addGap(66, 66, 66)
                                                .addComponent(cancelBtn)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentPWLabel)
                                        .addComponent(newPWLabel)
                                        .addComponent(confirmPWLabel))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(changePWLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(currentPWLabel)
                                        .addComponent(currentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newPWLabel)
                                        .addComponent(newTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(confirmPWLabel)
                                        .addComponent(confirmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(confirmBtn)
                                        .addComponent(cancelBtn))
                                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void cancelBtnActionPerformed(ActionEvent evt) {
        setVisible(false);
    }

    private void confirmBtnActionPerformed(ActionEvent evt) {
        String newPass=String.copyValueOf(newTxt.getPassword());
        String currentPass=String.copyValueOf(currentTxt.getPassword());
        String confirmPass=String.copyValueOf(confirmTxt.getPassword());

        if (!currentPass.equals(user.getPassUser()))
        {
            System.out.println(currentPass);
            System.out.println(user.getPassUser());
            JOptionPane.showMessageDialog(new CourseSystemFrame(),"The current password is incorrect.");
        }
        else
        {
            if (!newPass.equals(confirmPass)){
                JOptionPane.showMessageDialog(new CourseSystemFrame(),"The confirm password is incorrect.");
            }
            else{
                user.setPassUser(newPass);
                UsersDao.updateUser(user);
                if (user.getRole()==0) {
                    Teacher teacher = TeacherDao.getTeacher(user.getUsername());
                    teacher.setPasswordTc(user.getPassUser());
                    TeacherDao.updateTeacher(teacher);
                }
                else{
                    Student student = StudentDao.getStudent(user.getUsername());
                    student.setPasswordSt(user.getPassUser());
                    StudentDao.updateStudent(student);
                }
                JOptionPane.showMessageDialog(new CourseSystemFrame(),"Change password success.");
                setVisible(false);
            }
        }
    }



    // Variables declaration - do not modify
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel changePWLabel;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel confirmPWLabel;
    private javax.swing.JPasswordField confirmTxt;
    private javax.swing.JLabel currentPWLabel;
    private javax.swing.JPasswordField currentTxt;
    private java.awt.List list1;
    private javax.swing.JLabel newPWLabel;
    private javax.swing.JPasswordField newTxt;
    // End of variables declaration
}
