package gui;

import dao.UsersDao;
import gui.student.StudentMainForm;
import gui.teacher.TeacherMainForm;
import pojo.Users;

import javax.swing.*;
import java.awt.*;
public class SignInPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignInPanel
     */
    public SignInPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        signInLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        signInBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        signInLabel.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(117, 86, 253));
        signInLabel.setText("Sign In");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordLabel.setText("Password:");

        usernameTxt.setColumns(30);
        usernameTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userNameLabel.setText("Username:");

        passwordTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        signInBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        signInBtn.setText("Sign In");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(483, 483, 483)
                                .addComponent(signInBtn)
                                .addGap(95, 95, 95)
                                .addComponent(exitBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 433, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(userNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(passwordLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(408, 408, 408))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signInLabel)
                                .addGap(484, 484, 484))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(signInLabel)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userNameLabel)
                                        .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(signInBtn)
                                        .addComponent(exitBtn))
                                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Users sv = UsersDao.getUser(usernameTxt.getText());
        if (sv!=null) {
            String pass=String.copyValueOf(passwordTxt.getPassword());
            if (pass.equals(sv.getPassUser()))
            {
                if (sv.getRole()==0)
                {
                    JPanel panel=new TeacherMainForm(sv);
                    removeAll();
                    setLayout(new BorderLayout());
                    add(panel);
                    validate();
                    repaint();
                }
                else{
                    JPanel panel=new StudentMainForm(sv);
                    removeAll();
                    setLayout(new BorderLayout());
                    add(panel);
                    validate();
                    repaint();
                }
            }
            else{
                JOptionPane.showMessageDialog(new CourseSystemFrame(),"Password is incorrect.");
            }
        } else {
            JOptionPane.showMessageDialog(new CourseSystemFrame(),"Username is incorrect.");
        }
    }

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton signInBtn;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration
}


